SIA/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView

#from nucleo.views import inicio
from nucleo.views import *

from django.conf.urls.static import static
from django.conf.urls import url
from SIA.views import *
from SIA.views_reportes import *



urlpatterns = [
    url(r'^login/$', LoginView.as_view(template_name='adminlte/login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name='adminlte/login.html'), name='logout'),

    #url(r'^password_change/$', auth_views.password_change, name='password_change'),
    #url(r'^password_change/done/$', auth_views.password_change_done, name='password_change_done'),
    #url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    #url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),

    url(r'^formacion-academica/', include('formacion_academica.urls')),
    url(r'^experiencia/', include('experiencia_laboral.urls')),
    url(r'^investigacion/', include('investigacion.urls')),
    url(r'^difusion-cientifica/', include('difusion_cientifica.urls')),
    url(r'^divulgacion-cientifica/', include('divulgacion_cientifica.urls')),
    url(r'^vinculacion/', include('vinculacion.urls')),
    url(r'^docencia/', include('docencia.urls')),
    url(r'^apoyo-institucional/', include('apoyo_institucional.urls')),
    url(r'^movilidad-academica/', include('movilidad_academica.urls')),
    url(r'^formacion-recursos-humanos/', include('formacion_recursos_humanos.urls')),
    url(r'^desarrollos-tecnologicos/', include('desarrollo_tecnologico.urls')),
    url(r'^distinciones/', include('distinciones.urls')),
    url(r'^formatos/', include('formatos.urls')),
    url(r'^nucleo/', include('nucleo.urls')),

    url(r'^web/cv-investigadores/$', CVInvestigadorLista.as_view(), name='cv_investigador_lista'),
    url(r'^informe/$', Informe.as_view(), name='cv_investigador_lista'),

    url(r'^web/cv-investigadores/(?P<pk>[\w\-]+)/$', CVInvestigadorDetalle.as_view(), name='cv_investigador_detalle'),
    url(r'^web/cv-investigadores/(?P<pk>[\w\-]+)/pdf/$', CVInvestigadorPDF.as_view(), name='cv_investigador_detalle'),

    url(r'^web/publicaciones/$', WebPublicacionLista.as_view(), name='web_publicacion_lista'),
    url(r'^web/publicaciones/(?P<pk>[\w\-]+)/$', WebPublicacionDetalle.as_view(), name='web_publicacion_detalle'),

    url(r'^web/articulos/$', WebArticuloLista.as_view(), name='web_articulo_lista'),
    url(r'^web/articulos/(?P<pk>[\w\-]+)/$', WebArticuloDetalle.as_view(), name='web_articulo_detalle'),

    url(r'^web/proyectos/$', WebProyectoLista.as_view(), name='web_proyecto_lista'),
    url(r'^web/proyectos/(?P<pk>[\w\-]+)/$', WebProyectoDetalle.as_view(), name='web_proyecto_detalle'),



    url(r'^web/proyectos-actuales', PerfilUsuario.as_view(), name='perfil_usuario'),

    url(r'^perfil-usuario/(?P<pk>[\w\-]+)/$', PerfilUsuario.as_view(), name='perfil_usuario'),

    url(r'^reportes/historico$', ReporteHistorico.as_view(), name='reporte_historico'),
    url(r'^reportes/informe-actividades$', InformeActividades.as_view(), name='informe_actividades'),


    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^$', Dashboard.as_view(), name='dashboard'),
    url('^', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vinculacion/urls.py
from django.conf.urls import url
from . views import *


urlpatterns = [
    url(r'^arbitrajes-publicaciones/json/', ArbitrajePublicacionAcademicaJSON.as_view(), name='arbitraje_publicacion_academica_lista__json'),
    url(r'^arbitrajes-publicaciones/$', ArbitrajePublicacionAcademicaLista.as_view(), name='arbitraje_publicacion_academica_lista'),
    url(r'^arbitrajes-publicaciones/(?P<pk>[\w\-]+)/eliminar$', ArbitrajePublicacionAcademicaEliminar.as_view(), name='arbitraje_publicacion_academica_eliminar'),
    url(r'^arbitrajes-publicaciones/(?P<pk>[\w\-]+)/$', ArbitrajePublicacionAcademicaDetalle.as_view(), name='arbitraje_publicacion_academica_detalle'),

    url(r'^otras-comisiones/json/', OtraComisionJSON.as_view(), name='otra_comision_lista__json'),
    url(r'^otras-comisiones/$', OtraComisionLista.as_view(), name='otra_comision_lista'),
    url(r'^otras-comisiones/(?P<pk>[\w\-]+)/eliminar$', OtraComisionEliminar.as_view(), name='otra_comision_eliminar'),
    url(r'^otras-comisiones/(?P<pk>[\w\-]+)/$', OtraComisionDetalle.as_view(), name='otra_comision_detalle'),

    url(r'^redes-academicas/json/', RedAcademicaJSON.as_view(), name='red_academica_lista__json'),
    url(r'^redes-academicas/json-otros/', RedAcademicaJSON.as_view(otros=True), name='red_academica_lista_otros__json'),
    url(r'^redes-academicas/$', RedAcademicaLista.as_view(), name='red_academica_lista'),
    url(r'^redes-academicas/(?P<pk>[\w\-]+)/eliminar$', RedAcademicaEliminar.as_view(), name='red_academica_eliminar'),
    url(r'^redes-academicas/(?P<pk>[\w\-]+)/$', RedAcademicaDetalle.as_view(), name='red_academica_detalle'),

    url(r'^convenios-otras-entidades/json/', ConvenioOtraEntidadJSON.as_view(), name='convenio_otra_entidad_lista__json'),
    url(r'^convenios-otras-entidades/json-otros/', ConvenioOtraEntidadJSON.as_view(otros=True), name='convenio_otra_entidad_lista_otros__json'),
    url(r'^convenios-otras-entidades/$', ConvenioOtraEntidadLista.as_view(), name='convenio_otra_entidad_lista'),
    url(r'^convenios-otras-entidades/(?P<pk>[\w\-]+)/eliminar$', ConvenioOtraEntidadEliminar.as_view(), name='convenio_otra_entidad_eliminar'),
    url(r'^convenios-otras-entidades/(?P<pk>[\w\-]+)/$', ConvenioOtraEntidadDetalle.as_view(), name='convenio_otra_entidad_detalle'),

    url(r'^servicios-asesorias-externas/json/', ServicioAsesoriaExternaJSON.as_view(), name='servicio_asesoria_exterma_lista__json'),
    url(r'^servicios-asesorias-externas/$', ServicioAsesoriaExternaLista.as_view(), name='servicio_asesoria_exterma_lista'),
    url(r'^servicios-asesorias-externas/(?P<pk>[\w\-]+)/eliminar$', ServicioAsesoriaExternaEliminar.as_view(), name='servicio_asesoria_exterma_eliminar'),
    url(r'^servicios-asesorias-externas/(?P<pk>[\w\-]+)/$', ServicioAsesoriaExternaDetalle.as_view(), name='servicio_asesoria_exterma_detalle'),

]

vinculacion/models.py
from django.db import models
from django.conf import settings
from nucleo.models import User, Institucion, Dependencia, Revista, Indice, Financiamiento, \
    ProyectoInsvestigacionArbitrado, InstitucionSimple
from investigacion.models import ProyectoInvestigacion, ArticuloCientifico, LibroInvestigacion, CapituloLibroInvestigacion
from django.urls import reverse
from sortedm2m.fields import SortedManyToManyField


RED_ACADEMICA__AMBITO = getattr(settings, 'RED_ACADEMICA__AMBITO',
                                (('', '-------'), ('LOCAL', 'Local'), ('REGIONAL', 'Regional'),
                                        ('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional'), ('OTRO', 'Otro')))
CONVENIO_ENTIDAD_EXTERNA__CLASIFICACION = getattr(settings, 'CONVENIO_ENTIDAD_EXTERNA__CLASIFICACION',
                                                  (('', '-------'), ('FEDERAL', 'Gubernamental federal'),
                                                   ('ESTATAL', 'Gubernamental estatal'),
                                                   ('MUNICIPAL', 'Gubernamental municipal'),
                                                   ('PRIVADA', 'Sector privado'),
                                                   ('NO_LUCRATIVA', 'Sector privado no lucrativo'),
                                                   ('EXTRANJERA', 'Extranjero')))
ARBITRAJE_ACADEMICO__TIPO = getattr(settings, 'ARBITRAJE_ACADEMICA__TIPO',
                                    (('', '-------'), ('ARTICULO', 'Artículo en revista'), ('LIBRO', 'Libro'), ('CAPITULO_LIBRO', 'Capítulo de libro')))

STATUS_PROYECTO = getattr(settings, 'STATUS_PROYECTO', (('NUEVO', 'Nuevo'), ('EN_PROCESO', 'En proceso'),
                                                        ('CONCLUIDO', 'Concluído'), ('OTRO', 'Otro')))

# Create your models here.


class ArbitrajePublicacionAcademica(models.Model):
    tipo = models.CharField(max_length=20, choices=ARBITRAJE_ACADEMICO__TIPO)
    revista = models.ForeignKey(Revista, blank=True, null=True, on_delete=models.DO_NOTHING)
    libro = models.CharField(max_length=255, blank=True, null=True)
    capitulo_libro = models.CharField(max_length=255, blank=True, null=True)
    fecha_dictamen = models.DateField()
    institucion = models.ForeignKey(InstitucionSimple, blank=True, null=True, on_delete=models.DO_NOTHING)
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.fecha_dictamen

    def get_absolute_url(self):
        return reverse('arbitraje_publicacion_academica_detalle', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-fecha_dictamen']
        verbose_name = 'Arbitraje en publicaciones académicas'
        verbose_name_plural = 'Arbitrajes en publicaciones académicas'

class ComisionVinculacion(models.Model):
    comisionvinculacion_nombre = models.CharField(max_length=140, unique=True)
    comisionvinculacion_orden = models.IntegerField()

    def __str__(self):
        return self.comisionvinculacion_nombre

    def natural_key(self):
        return self.comisionvinculacion_nombre

    class Meta:
        ordering = ['comisionvinculacion_orden', 'id']


class OtraComision(models.Model):
    comision = models.ForeignKey(ComisionVinculacion, on_delete=models.DO_NOTHING)
    comision_otra = models.CharField(max_length=255, blank=True, null=True)
    institucion = models.ForeignKey(InstitucionSimple, on_delete=models.DO_NOTHING, null=True, blank=True)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return "{} : {}".format(self.comision_otra, self.institucion)

    def get_absolute_url(self):
        return reverse('otra_comision_detalle', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-fecha_inicio']
        verbose_name = 'Otra comisión de arbitraje'
        verbose_name_plural = 'Otras comisiones de arbitraje'


class RedAcademica(models.Model):
    nombre = models.CharField(max_length=255, unique=True)
    ambito = models.CharField(max_length=20, choices=RED_ACADEMICA__AMBITO)
    objetivos = models.TextField()
    fecha_constitucion = models.DateField()
    fecha_fin = models.DateField(null=True, blank=True)
    instituciones = models.ManyToManyField(InstitucionSimple)
    proyecto = models.ForeignKey(ProyectoInvestigacion, blank=True, null=True, on_delete=models.DO_NOTHING)
    participantes = models.ManyToManyField(User, related_name='red_academica_participantes', verbose_name='Académicos participantes')

    def __str__(self):
        return "{} : {}".format(self.nombre, self.fecha_constitucion)

    def get_absolute_url(self):
        return reverse('red_academica_detalle', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-fecha_constitucion']
        verbose_name = 'Red académica'
        verbose_name_plural = 'Redes académicas'


class ConvenioOtraEntidad(models.Model):
    nombre = models.CharField(max_length=254, unique=True)
    instituciones = models.ManyToManyField(InstitucionSimple)
    objetivos = models.TextField()
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField(blank=True, null=True)
    es_renovacion = models.BooleanField(blank=True, default=False)
    financiamiento_text = models.CharField(max_length=254, blank=True, null=True)
    proyecto = models.ForeignKey(ProyectoInvestigacion, on_delete=models.DO_NOTHING, blank=True, null=True)
    ambito = models.CharField(max_length=20, choices=(('', '-------'), ('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'INTERNACIONAL')))
    participantes = models.ManyToManyField(User, verbose_name='Académicos participantes')

    def __str__(self):
        return "{} : {}".format(self.nombre, self.fecha_inicio)

    def get_absolute_url(self):
        return reverse('convenio_otra_entidad_detalle', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-fecha_inicio']
        verbose_name = 'Convenio con otra entidad'
        verbose_name_plural = 'Convenios con otras entidades'


class ServicioAsesoriaExterna(models.Model):
    nombre_servicio = models.CharField(max_length=254)
    descripcion = models.TextField(blank=True)
    institucion = models.ForeignKey(InstitucionSimple, on_delete=models.DO_NOTHING)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    financiamiento_text = models.CharField(max_length=254)
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return "{} : {}".format(self.nombre_servicio, self.fecha_inicio)

    def get_absolute_url(self):
        return reverse('servicio_asesoria_exterma_detalle', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-fecha_inicio']
        verbose_name = 'Servicio o asesoria externa'
        verbose_name_plural = 'Servicios o asesorias externas'

vinculacion/templates/arbitraje_otra_actividad.html
{% extends 'main.html' %}

{% block form_agregar %}
    <p><strong>Actividad de arbitraje:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Actividad de arbitraje.">
            <i class="fa fa-question-circle"></i>
        </a> <i class="fa fa-edit"></i>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group date">
            <div class="input-group-addon">
                <i class="fa fa-pencil-square-o"></i>
            </div>
            {{ form.actividad }}
        </div>
    </div>
    </p>
    <p><strong>Descripción: <a href="#" data-toggle="tooltip" data-placement="right"
                               title="Descripción detallada adicional, por ejemplo información que no está contemplada en los demás campos.">
        <i class="fa fa-question-circle"></i></a></strong>
        {{ form.descripcion }}
    </p>
    <p><strong>Dependencia:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Dependencia donde se llevó a cabo el arbitraje, las opciones
                                              disponibles están en función de la institución seleccionada en el campo
                                              anterior. Si no se selecciona una institución, se enlistan todas las
                                              dependencias pero no se puede saber a cual institución pertenecen. En caso de no existir una dependencia hija de una institución, es necesario que exista entonces una dependencia con el mismo nombre que la institución y que pertenezca a ella.">
            <i class="fa fa-question-circle"></i></a> <i class="fa fa-edit"></i>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-list-alt"></i></div>
            {{ form.dependencia }}
            <div class="input-group-addon">
                <a href="#" data-toggle="tooltip" data-placement="left"
                   title="Mostrar los detalles adicionales al nombre de la dependencia.">
                    <i class="fa fa-eye"></i>
                </a>
            </div>
            <div class="input-group-addon">
                <a href="/nucleo/dependencias" data-toggle="tooltip" data-placement="left" target="_blank"
                   title="Agregar una dependencia nueva. Cuando no existe en los registros aquí se puede dar de alta.">
                    <i class="fa fa-plus"></i>
                </a>
            </div>
        </div>
    </div>
    </p>
    <p><strong>Fecha:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Fecha de dictamen del arbitraje."><i
                class="fa fa-question-circle"></i></a> <i class="fa fa-edit"></i>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group date">
            <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
            </div>
            {{ form.fecha }}
        </div>
    </div>
    </p>
{% endblock %}

{% block form_detalle %}
    <p><strong>Actividad de arbitraje:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Actividad de arbitraje.">
            <i class="fa fa-question-circle"></i>
        </a> <i class="fa fa-edit"></i>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group date">
            <div class="input-group-addon">
                <i class="fa fa-pencil-square-o"></i>
            </div>
            {{ form.actividad }}
        </div>
    </div>
    </p>
    <p><strong>Descripción: <a href="#" data-toggle="tooltip" data-placement="right"
                               title="Descripción detallada adicional, por ejemplo información que no está contemplada en los demás campos.">
        <i class="fa fa-question-circle"></i></a></strong>
        {{ form.descripcion }}
    </p>
    <p><strong>Dependencia:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Dependencia donde se llevó a cabo el arbitraje, las opciones
                                              disponibles están en función de la institución seleccionada en el campo
                                              anterior. Si no se selecciona una institución, se enlistan todas las
                                              dependencias pero no se puede saber a cual institución pertenecen. En caso de no existir una dependencia hija de una institución, es necesario que exista entonces una dependencia con el mismo nombre que la institución y que pertenezca a ella.">
            <i class="fa fa-question-circle"></i></a> <i class="fa fa-edit"></i>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-list-alt"></i></div>
            {{ form.dependencia }}
            <div class="input-group-addon">
                <a href="#" data-toggle="tooltip" data-placement="left"
                   title="Mostrar los detalles adicionales al nombre de la dependencia.">
                    <i class="fa fa-eye"></i>
                </a>
            </div>
            <div class="input-group-addon">
                <a href="/nucleo/dependencias" data-toggle="tooltip" data-placement="left" target="_blank"
                   title="Agregar una dependencia nueva. Cuando no existe en los registros aquí se puede dar de alta.">
                    <i class="fa fa-plus"></i>
                </a>
            </div>
        </div>
    </div>
    </p>
    <p><strong>Fecha:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Fecha de dictamen del arbitraje."><i
                class="fa fa-question-circle"></i></a> <i class="fa fa-edit"></i>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group date">
            <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
            </div>
            {{ form.fecha }}
        </div>
    </div>
    </p>
{% endblock %}

vinculacion/templates/arbitraje_publicacion.html
{% extends 'main.html' %}

{% block form_agregar %}
    <p><strong>Descripción: <a href="#" data-toggle="tooltip" data-placement="right"
                               title="Descripción detallada adicional, por ejemplo información que no está contemplada en los demás campos.">
        <i class="fa fa-question-circle"></i></a></strong>
        {{ form.descripcion }}
    </p>
    <p><strong>Tipo:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Tipo de publicación arbitrada, puede ser un libro, una revista, o un capitulo de libro."><i
                class="fa fa-question-circle"></i></a>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-list-alt"></i></div>
            {{ form.tipo }}
        </div>
    </div>
    </p>
    <div id="d_articulo">
        <p><strong>Artículo:</strong>
            <a href="#" data-toggle="tooltip" data-placement="right"
               title="Artículo sobre el que se realizó el dictamen."><i class="fa fa-question-circle"></i></a>
        <div class="form-group" style="margin-top: -10px;">
            <div class="input-group">
                <div class="input-group-addon"><i class="fa fa-list-alt"></i></div>
                {{ form.articulo }}
                <div class="input-group-addon">
                    <a href="#" data-toggle="tooltip" data-placement="left"
                       title="Mostrar los detalles adicionales del artículo seleccionado.">
                        <i class="fa fa-eye"></i>
                    </a>
                </div>
                <div class="input-group-addon">
                    <a href="/investigacion/revistas" data-toggle="tooltip" data-placement="left" target="_blank"
                       title="Agregar un artículo nuevo. Cuando no existe en los registros, aquí se puede dar de alta.">
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
        </div>
        </p>
    </div>
    <div id="d_libro">
        <p><strong>Libro:</strong>
            <a href="#" data-toggle="tooltip" data-placement="right"
               title="Nombre del libro del arbitraje."><i class="fa fa-question-circle"></i></a>
        <div class="form-group" style="margin-top: -10px;">
            <div class="input-group">
                <div class="input-group-addon"><i class="fa fa-list-alt"></i></div>
                {{ form.libro }}
                <div class="input-group-addon">
                    <a href="/nucleo/libros" data-toggle="tooltip" data-placement="left"
                       title="Mostrar los detalles adicionales del libro seleccionado.">
                        <i class="fa fa-eye"></i>
                    </a>
                </div>
                <div class="input-group-addon">
                    <a href="/investigacion/libros-publicados" data-toggle="tooltip" data-placement="left"
                       target="_blank"
                       title="Agregar un libro nuevo. Cuando no existe en los registros, aquí se puede dar de alta.">
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
        </div>
        </p>
    </div>
    <p><strong>Fecha de dictamen:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Fecha de dictamen del arbitraje."><i
                class="fa fa-question-circle"></i></a>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group date">
            <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
            </div>
            {{ form.fecha_dictamen }}
        </div>
    </div>
    </p>

    <script>
        $('#d_libro').hide();
        $('#d_articulo').hide();

        $("#id_tipo").on('change', function () {
                    if ($("#id_tipo").val() == 'LIBRO') {
                        $('#d_libro').show('slow');
                        $('#id_libro').attr("required", "true");
                        $('#id_articulo').attr("required", null);
                        $('#id_articulo').val(null).trigger("change");
                        $('#d_articulo').hide('slow');
                    } else if ($("#id_tipo").val() == 'ARTICULO') {
                        $('#d_articulo').show('slow');
                        $('#id_libro').attr("required", null);
                        $('#id_articulo').attr("required", "true");
                        $('#id_libro').val(null).trigger("change");
                        $('#d_libro').hide('slow');
                    } else {
                        $('#d_articulo').show();
                        $('#d_libro').show();
                        $('#id_libro').attr("required", null);
                        $('#id_articulo').attr("required", null);
                    }
                });
    </script>


{% endblock %}

{% block form_detalle %}
    <p><strong>Descripción: <a href="#" data-toggle="tooltip" data-placement="right"
                               title="Descripción detallada adicional, por ejemplo información que no está contemplada en los demás campos.">
        <i class="fa fa-question-circle"></i></a></strong>
        {{ form.descripcion }}
    </p>
    <p><strong>Tipo:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Tipo de publicación arbitrada, puede ser un libro, una revista, o un capitulo de libro."><i
                class="fa fa-question-circle"></i></a>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-list-alt"></i></div>
            {{ form.tipo }}
        </div>
    </div>
    </p>
    <div id="d_articulo">
        <p><strong>Artículo:</strong>
            <a href="#" data-toggle="tooltip" data-placement="right"
               title="Artículo sobre el que se realizó el dictamen."><i class="fa fa-question-circle"></i></a>
        <div class="form-group" style="margin-top: -10px;">
            <div class="input-group">
                <div class="input-group-addon"><i class="fa fa-list-alt"></i></div>
                {{ form.articulo }}
                <div class="input-group-addon">
                    <a href="#" data-toggle="tooltip" data-placement="left"
                       title="Mostrar los detalles adicionales del artículo seleccionado.">
                        <i class="fa fa-eye"></i>
                    </a>
                </div>
                <div class="input-group-addon">
                    <a href="/investigacion/revistas" data-toggle="tooltip" data-placement="left" target="_blank"
                       title="Agregar un artículo nuevo. Cuando no existe en los registros, aquí se puede dar de alta.">
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
        </div>
        </p>
    </div>
    <div id="d_libro">
        <p><strong>Libro:</strong>
            <a href="#" data-toggle="tooltip" data-placement="right"
               title="Nombre del libro del arbitraje."><i class="fa fa-question-circle"></i></a>
        <div class="form-group" style="margin-top: -10px;">
            <div class="input-group">
                <div class="input-group-addon"><i class="fa fa-list-alt"></i></div>
                {{ form.libro }}
                <div class="input-group-addon">
                    <a href="/nucleo/libros" data-toggle="tooltip" data-placement="left"
                       title="Mostrar los detalles adicionales del libro seleccionado.">
                        <i class="fa fa-eye"></i>
                    </a>
                </div>
                <div class="input-group-addon">
                    <a href="/investigacion/libros-publicados" data-toggle="tooltip" data-placement="left"
                       target="_blank"
                       title="Agregar un libro nuevo. Cuando no existe en los registros, aquí se puede dar de alta.">
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
        </div>
        </p>
    </div>
    <p><strong>Fecha de dictamen:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Fecha de dictamen del arbitraje."><i
                class="fa fa-question-circle"></i></a>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group date">
            <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
            </div>
            {{ form.fecha_dictamen }}
        </div>
    </div>
    </p>

    <script>
        $('#d_revista').hide();
        $('#d_libro').hide();

        if ($("#id_tipo").val() == 'ARTICULO') {
            $('#d_articulo').show();
            $('#id_articulo').attr("required", "true");
        } else if ($("#id_tipo").val() == 'LIBRO') {
            $('#d_libro').show();
            $('#id_libro').attr("required", "true");
        } else {
            $('#d_articulo').show();
            $('#d_libro').show();
            $('#id_libro').attr("required", null);
            $('#id_articulo').attr("required", null);
        }

        $("#id_tipo").on('change', function () {
                    if ($("#id_tipo").val() == 'LIBRO') {
                        $('#d_libro').show('slow');
                        $('#id_libro').attr("required", "true");
                        $('#id_articulo').attr("required", null);
                        $('#id_articulo').val(null).trigger("change");
                        $('#d_articulo').hide('slow');
                    } else if ($("#id_tipo").val() == 'ARTICULO') {
                        $('#d_articulo').show('slow');
                        $('#id_libro').attr("required", null);
                        $('#id_articulo').attr("required", "true");
                        $('#id_libro').val(null).trigger("change");
                        $('#d_libro').hide('slow');
                    } else {
                        $('#d_articulo').show();
                        $('#d_libro').show();
                        $('#id_libro').attr("required", null);
                        $('#id_articulo').attr("required", null);
                    }
                });
    </script>

{% endblock %}