SIA/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView

#from nucleo.views import inicio
from nucleo.views import *

from django.conf.urls.static import static
from django.conf.urls import url
from SIA.views import *
from SIA.views_reportes import *



urlpatterns = [
    url(r'^login/$', LoginView.as_view(template_name='adminlte/login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name='adminlte/login.html'), name='logout'),

    #url(r'^password_change/$', auth_views.password_change, name='password_change'),
    #url(r'^password_change/done/$', auth_views.password_change_done, name='password_change_done'),
    #url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    #url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),

    url(r'^formacion-academica/', include('formacion_academica.urls')),
    url(r'^experiencia/', include('experiencia_laboral.urls')),
    url(r'^investigacion/', include('investigacion.urls')),
    url(r'^difusion-cientifica/', include('difusion_cientifica.urls')),
    url(r'^divulgacion-cientifica/', include('divulgacion_cientifica.urls')),
    url(r'^vinculacion/', include('vinculacion.urls')),
    url(r'^docencia/', include('docencia.urls')),
    url(r'^apoyo-institucional/', include('apoyo_institucional.urls')),
    url(r'^movilidad-academica/', include('movilidad_academica.urls')),
    url(r'^formacion-recursos-humanos/', include('formacion_recursos_humanos.urls')),
    url(r'^desarrollos-tecnologicos/', include('desarrollo_tecnologico.urls')),
    url(r'^distinciones/', include('distinciones.urls')),
    url(r'^formatos/', include('formatos.urls')),
    url(r'^nucleo/', include('nucleo.urls')),

    url(r'^web/cv-investigadores/$', CVInvestigadorLista.as_view(), name='cv_investigador_lista'),
    url(r'^informe/$', Informe.as_view(), name='cv_investigador_lista'),

    url(r'^web/cv-investigadores/(?P<pk>[\w\-]+)/$', CVInvestigadorDetalle.as_view(), name='cv_investigador_detalle'),
    url(r'^web/cv-investigadores/(?P<pk>[\w\-]+)/pdf/$', CVInvestigadorPDF.as_view(), name='cv_investigador_detalle'),

    url(r'^web/publicaciones/$', WebPublicacionLista.as_view(), name='web_publicacion_lista'),
    url(r'^web/publicaciones/(?P<pk>[\w\-]+)/$', WebPublicacionDetalle.as_view(), name='web_publicacion_detalle'),

    url(r'^web/articulos/$', WebArticuloLista.as_view(), name='web_articulo_lista'),
    url(r'^web/articulos/(?P<pk>[\w\-]+)/$', WebArticuloDetalle.as_view(), name='web_articulo_detalle'),

    url(r'^web/proyectos/$', WebProyectoLista.as_view(), name='web_proyecto_lista'),
    url(r'^web/proyectos/(?P<pk>[\w\-]+)/$', WebProyectoDetalle.as_view(), name='web_proyecto_detalle'),



    url(r'^web/proyectos-actuales', PerfilUsuario.as_view(), name='perfil_usuario'),

    url(r'^perfil-usuario/(?P<pk>[\w\-]+)/$', PerfilUsuario.as_view(), name='perfil_usuario'),

    url(r'^reportes/historico$', ReporteHistorico.as_view(), name='reporte_historico'),
    url(r'^reportes/informe-actividades$', InformeActividades.as_view(), name='informe_actividades'),


    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^$', Dashboard.as_view(), name='dashboard'),
    url('^', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

divulgacion_cientifica/urls.py
from django.conf.urls import url
from . views import *

urlpatterns = [

    url(r'^articulos-divulgacion/json/', ArticuloDivulgacionJSON.as_view(), name='articulo_divulgacion_lista__json'),
    url(r'^articulos-divulgacion/json-otros/', ArticuloDivulgacionJSON.as_view(otros=True), name='articulo_divulgacion_lista_otros__json'),
    url(r'^articulos-divulgacion/$', ArticuloDivulgacionLista.as_view(), name='articulo_divulgacion_lista'),
    url(r'^articulos-divulgacion/(?P<pk>[\w\-]+)/eliminar$', ArticuloDivulgacionEliminar.as_view(), name='articulo_divulgacion_eliminar'),
    url(r'^articulos-divulgacion/(?P<pk>[\w\-]+)/$', ArticuloDivulgacionDetalle.as_view(), name='articulo_divulgacion_detalle'),

    url(r'^libros-divulgacion/json/', LibroDivulgacionJSON.as_view(), name='libro_investigacion_lista__json'),
    url(r'^libros-divulgacion/json-otros/', LibroDivulgacionJSON.as_view(otros=True), name='libro_investigacion_lista_otros__json'),
    url(r'^libros-divulgacion/$', LibroDivulgacionLista.as_view(), name='libro_investigacion_lista'),
    url(r'^libros-divulgacion/(?P<pk>[\w\-]+)/eliminar$', LibroDivulgacionEliminar.as_view(), name='libro_investigacion_eliminar'),
    url(r'^libros-divulgacion/(?P<pk>[\w\-]+)/$', LibroDivulgacionDetalle.as_view(), name='libro_investigacion_detalle'),

    url(r'^capitulos-libros-divulgacion/json/', CapituloLibroDivulgacionJSON.as_view(), name='capitulo_libro_divulgacion_lista__json'),
    url(r'^capitulos-libros-divulgacion/json-otros/', CapituloLibroDivulgacionJSON.as_view(otros=True), name='capitulo_libro_divulgacion_lista_otros__json'),
    url(r'^capitulos-libros-divulgacion/$', CapituloLibroDivulgacionLista.as_view(), name='capitulo_libro_divulgacion_lista'),
    url(r'^capitulos-libros-divulgacion/(?P<pk>[\w\-]+)/eliminar$', CapituloLibroDivulgacionEliminar.as_view(), name='capitulo_libro_divulgacion_eliminar'),
    url(r'^capitulos-libros-divulgacion/(?P<pk>[\w\-]+)/$', CapituloLibroDivulgacionDetalle.as_view(), name='capitulo_libro_divulgacion_detalle'),

    url(r'^organizacion-eventos-divulgacion/json/', OrganizacionEventoDivulgacionJSON.as_view(), name='organizacion_evento_divulgacion_lista__json'),
    #url(r'^organizacion-eventos-divulgacion/json-otros/', OrganizacionEventoDivulgacionJSON.as_view(otros=True), name='organizacion_evento_divulgacion_lista_otros__json'),
    url(r'^organizacion-eventos-divulgacion/$', OrganizacionEventoDivulgacionLista.as_view(), name='organizacion_evento_divulgacion_lista'),
    url(r'^organizacion-eventos-divulgacion/(?P<pk>[\w\-]+)/eliminar$', OrganizacionEventoDivulgacionEliminar.as_view(), name='organizacion_evento_divulgacion_eliminar'),
    url(r'^organizacion-eventos-divulgacion/(?P<pk>[\w\-]+)/$', OrganizacionEventoDivulgacionDetalle.as_view(), name='organizacion_evento_divulgacion_detalle'),

    url(r'^participacion-eventos-divulgacion/json/', ParticipacionEventoDivulgacionJSON.as_view(), name='participacion_evento_divulgacion_lista__json'),
    url(r'^participacion-eventos-divulgacion/json-otros/', ParticipacionEventoDivulgacionJSON.as_view(otros=True), name='participacion_evento_divulgacion_lista_otros__json'),
    url(r'^participacion-eventos-divulgacion/$', ParticipacionEventoDivulgacionLista.as_view(), name='participacion_evento_divulgacion_lista'),
    url(r'^participacion-eventos-divulgacion/(?P<pk>[\w\-]+)/eliminar$', ParticipacionEventoDivulgacionEliminar.as_view(), name='participacion_evento_divulgacion_eliminar'),
    url(r'^participacion-eventos-divulgacion/(?P<pk>[\w\-]+)/$', ParticipacionEventoDivulgacionDetalle.as_view(), name='participacion_evento_divulgacion_detalle'),

    url(r'^medios-divulgacion/json/', ProgramaRadioTelevisionInternetJSON.as_view(), name='programa_radio_television_internet_lista__json'),
    url(r'^medios-divulgacion/$', ProgramaRadioTelevisionInternetLista.as_view(), name='programa_radio_television_internet_lista'),
    url(r'^medios-divulgacion/(?P<pk>[\w\-]+)/eliminar$', ProgramaRadioTelevisionInternetEliminar.as_view(), name='programa_radio_television_internet_eliminar'),
    url(r'^medios-divulgacion/(?P<pk>[\w\-]+)/$', ProgramaRadioTelevisionInternetDetalle.as_view(), name='programa_radio_television_internet_detalle'),

    url(r'^rest/eventos-divulgacion/$', RESTEventoDivulgacionLista.as_view()),
    url(r'^rest/eventos-divulgacion/(?P<pk>[0-9]+)/$', RESTEventoDivulgacionDetalle.as_view()),

    url(r'^eventos-divulgacion/agregar/$', EventoDivulgacionAgregar.as_view(), name='institucion_agregar'),
    url(r'^eventos-divulgacion/(?P<pk>[\w\-]+)/$', EventoDivulgacionDetalle.as_view(), name='institucion_detalle'),
]

divulgacion_cientifica/models.py
from django.db import models
from django.conf import settings
from nucleo.models import User, Evento, TipoEvento, Pais, Libro, Revista, InstitucionSimple, RevistaDivulgacion, Indice, MedioDivulgacion, Financiamiento
from investigacion.models import ProyectoInvestigacion
from django.urls import reverse
from sortedm2m.fields import SortedManyToManyField

EVENTO__AMBITO = getattr(settings, 'EVENTO__AMBITO', (('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional')))
STATUS_PUBLICACION_LIBRO = getattr(settings, 'STATUS_PUBLICACION_LIBRO', (('', '-------'), ('ENVIADO', 'Enviado'), ('ACEPTADO', 'Aceptado'), ('EN_PRENSA', 'En prensa'), ('PUBLICADO', 'Publicado')))

STATUS_PUBLICACION = (('', '-------'), ('ENVIADO', 'Enviado'), ('ACEPTADO', 'Aceptado'), ('EN_PRENSA', 'En prensa'), ('PUBLICADO', 'Publicado'))


# Create your models here.

class ArticuloDivulgacion(models.Model):
    titulo = models.CharField(max_length=255, unique=True)
    status = models.CharField(max_length=20, choices=STATUS_PUBLICACION)
    autores = SortedManyToManyField(User, related_name='articulo_divulgacion_autores', verbose_name='Autores')
    autores_todos = models.TextField()
    agradecimientos = models.ManyToManyField(User, related_name='articulo_divulgacion_agradecimientos', blank=True)
    url = models.URLField(blank=True)
    solo_electronico = models.BooleanField(default=False)
    revista_divulgacion = models.ForeignKey(RevistaDivulgacion, related_name='articulodivulgacion_revistadivulgacion', on_delete=models.DO_NOTHING)
    fecha = models.DateField(null=True, blank=True)
    fecha_enviado = models.DateField(null=True, blank=True)
    fecha_aceptado = models.DateField(null=True, blank=True)
    fecha_enprensa = models.DateField(null=True, blank=True)
    fecha_publicado = models.DateField(null=True, blank=True)
    pagina_inicio = models.PositiveIntegerField()
    pagina_fin = models.PositiveIntegerField()
    numero = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return "{} : {}".format(self.titulo, self.revista_divulgacion)

    def get_absolute_url(self):
        return reverse('articulo_divulgacion_detalle', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = "Artículo de divulgación"
        verbose_name_plural = "Artículos de divulgación"
        ordering = ['fecha', 'titulo']


class CapituloLibroDivulgacion(models.Model):
    titulo = models.CharField(max_length=255)
    libro = models.ForeignKey(Libro, on_delete=models.DO_NOTHING)
    pagina_inicio = models.PositiveIntegerField()
    pagina_fin = models.PositiveIntegerField()
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True)
    autores = SortedManyToManyField(User, related_name='capitulo_libro_divulgacion_autores', verbose_name='Autores')
    autores_todos = models.TextField(blank=True, null=True)

    def __str__(self):
        return "{} : {}".format(self.titulo, self.libro)

    def get_absolute_url(self):
        return reverse('capitulo_libro_divulgacion_detalle', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = "Capítulo en libro de divulgación"
        verbose_name_plural = "Capítulos en libros de divulgración"
        ordering = ['titulo']
        unique_together = ['titulo', 'libro']


class EventoDivulgacion(models.Model):
    eventodivulgacion_nombre = models.CharField(max_length=255)
    eventodivulgacion_tipo = models.ForeignKey(TipoEvento, on_delete=models.PROTECT)
    eventodivulgacion_fecha_inicio = models.DateField()
    eventodivulgacion_fecha_fin = models.DateField()
    eventodivulgacion_pais = models.ForeignKey(Pais, on_delete=models.PROTECT)
    eventodivulgacion_ciudad = models.CharField(max_length=255)
    eventodivulgacion_ambito = models.CharField(max_length=20, choices=EVENTO__AMBITO)
    eventodivulgacion_numeroponentes = models.PositiveIntegerField()
    eventodivulgacion_numeroasistentes = models.PositiveIntegerField()

    def __str__(self):
        return self.eventodivulgacion_nombre

    def natural_key(self):
        return self.eventodivulgacion_nombre

    def get_absolute_url(self):
        return reverse('eventodivulgacion_detalle', kwargs={'pk': self.pk})

    class Meta:
        unique_together = ['eventodivulgacion_fecha_inicio', 'eventodivulgacion_nombre']




class OrganizacionEventoDivulgacion(models.Model):
    evento2 = models.ForeignKey(Evento, on_delete=models.DO_NOTHING)
    evento = models.ForeignKey(EventoDivulgacion, blank=True, null=True, related_name='OrganizacionEventoAcademico_evento', on_delete=models.DO_NOTHING)

    tipo_participacion = models.CharField(
        max_length=50,
        choices=(('', '-------'), ('COORDINADOR', 'Coordinador general'), ('COMITE_ORGANIZADOR', 'Comité organizador'),
                 ('APOYO_TECNICO', 'Apoyo técnico'), ('OTRO', 'Otro tipo de participaciòn')))
    tipo_participacion_otro = models.CharField(max_length=254, blank=True, null=True)
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    coordinador_general = models.ForeignKey(User, blank=True, null=True, related_name='organizacion_evento_divulgacion_coordinador_general', on_delete=models.DO_NOTHING, verbose_name='Coordinador general')
    comite_organizador = SortedManyToManyField(User, blank=True, related_name='organizacion_evento_divulgacion_comite_organizador', verbose_name='Comite organizador')
    apoyo_tecnico = SortedManyToManyField(User, blank=True, related_name='organizacion_evento_divulgacion_apoyo_tecnico', verbose_name='Apoyo técnico')

    def __str__(self):
        return "{}, {}".format(self.evento2, self.tipo_participacion)

    def get_absolute_url(self):
        return reverse('organizacion_evento_divulgacion_detalle', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Organización de evento de divulgación'
        verbose_name_plural = 'Organización de eventos de divulgación'


class ParticipacionEventoDivulgacion(models.Model):
    tipo = models.CharField(max_length=30, choices=(('', '------'), ('PONENCIA', 'Ponencia'), ('POSTER', 'Poster')))
    titulo = models.CharField(max_length=255)
    evento = models.ForeignKey(Evento, on_delete=models.DO_NOTHING)

    evento_text = models.CharField(max_length=254, blank=True, null=True, verbose_name='Nombre del evento')
    lugar_evento = models.CharField(max_length=254, blank=True, null=True, verbose_name='Lugar del evento')
    institucion = models.ForeignKey(InstitucionSimple, on_delete=models.DO_NOTHING, null=True, blank=True)
    fecha = models.DateField()

    ambito = models.CharField(max_length=20, choices=EVENTO__AMBITO)
    por_invitacion = models.BooleanField(default=False)
    ponencia_magistral = models.BooleanField(default=False)
    autores = models.ManyToManyField(User, related_name='participacion_evento_divulgacion_autores')

    # tags = models.ManyToManyField(Tag, related_name='participacion_evento_tags', blank=True)

    def __str__(self):
        return "{} : {}".format(self.titulo, self.evento)

    def get_absolute_url(self):
        return reverse('participacion_evento_divulgacion_detalle', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Participación en evento académico'
        verbose_name_plural = 'Participación en eventos académicos'


class ProgramaRadioTelevisionInternet(models.Model):
    tema = models.CharField(max_length=254)
    fecha = models.DateField()
    descripcion = models.TextField(blank=True)
    actividad = models.CharField(max_length=20, choices=(
        ('PRODUCCION', 'Producción'), ('PARTICIPACION', 'Participación'), ('ENTREVISTA', 'Entrevista'),
        ('OTRA', 'Otra')))
    medio_divulgacion = models.ForeignKey(MedioDivulgacion, blank=True, null=True, on_delete=models.DO_NOTHING)
    medio_divulgacion_text = models.CharField(max_length=254, blank=True, null=True)
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return "{} : {} : {}".format(self.medio_divulgacion.nombre_medio, self.tema, self.fecha)

    def get_absolute_url(self):
        return reverse('programa_radio_television_internet_detalle', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['fecha', 'tema']
        verbose_name = 'Programa de radio, televisión, internet o medios impresos'
        verbose_name_plural = 'Programas de radio, televisión, internet o medios impresos'

divulgacion_cientifica/templates/capitulo_libro_divulgacion.html
{% extends 'main.html' %}

{% block form_agregar %}
    <p><strong>Título del capítulo:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Título del capítulo, no del libro.">
            <i class="fa fa-question-circle"></i>
        </a> <i class="fa fa-edit"></i>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group date">
            <div class="input-group-addon">
                <i class="fa fa-pencil-square-o"></i>
            </div>
            {{ form.titulo }}
        </div>
    </div>
    </p>
    <p><strong>Libro:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Libro al que pertenece el capítulo escrito.">
            <i class="fa fa-question-circle"></i>
        </a> <i class="fa fa-edit"></i>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-book"></i></div>
            {{ form.libro }}
            <div class="input-group-addon">
                <a href="/nucleo/libros" data-toggle="tooltip" data-placement="left"
                   title="Mostrar los detalles adicionales del libro seleccionado.">
                    <i class="fa fa-eye"></i>
                </a>
            </div>
            <div class="input-group-addon">
                <a href="/divulgacion-cientifica/libros-divulgacion" data-toggle="tooltip" data-placement="left"
                   title="Agregar un libro nuevo. Cuando no existe en los registros, aquí se puede dar de alta.">
                    <i class="fa fa-plus"></i>
                </a>
            </div>
        </div>
    </div>
    </p>
    <p><strong>Autores del capítulo:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Autores del capítulo, sólo autores que estén adscritos al CIGA.">
            <i class="fa fa-question-circle"></i></a> <i class="fa fa-edit"></i>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-users"></i></div>
            {{ form.autores }}
            <div class="input-group-addon">
                <a href="#" data-toggle="tooltip" data-placement="left"
                   title="Mostrar los detalles adicionales de los autores.">
                    <i class="fa fa-eye"></i>
                </a>
            </div>
            <div class="input-group-addon">
                <a href="/nucleo/usuarios/" data-toggle="tooltip" data-placement="left" target="_blank"
                   title="Agregar un autor nuevo. Cuando no existe en los registros, aquí se puede dar de alta.">
                    <i class="fa fa-plus"></i>
                </a>
            </div>
        </div>
    </div>
    </p>
    <p><strong>Autores como se reportan en el capítulo: <a href="#" data-toggle="tooltip" data-placement="right"
                                                        title="Autores tal cual se reportan en el capítulo, en el orden y forma.">
        <i class="fa fa-question-circle"></i></a></strong>
        {{ form.autores_todos }}
    </p>
    <p><strong>Página inicial:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Número de página donde inicia el capítulo.">
            <i class="fa fa-question-circle"></i></a> <i class="fa fa-edit"></i>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group date">
            <div class="input-group-addon"><i class="fa fa-sort-numeric-desc"></i></div>
            {{ form.pagina_inicio }}
        </div>
    </div>
    </p>
    <p><strong>Página final:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Número de página donde finaliza el capítulo.">
            <i class="fa fa-question-circle"></i></a> <i class="fa fa-edit"></i>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group date">
            <div class="input-group-addon"><i class="fa fa-sort-numeric-desc"></i></div>
            {{ form.pagina_fin }}
        </div>
    </div>
    </p>

    <script>
        //$("#id_usuarios").select2();
        $("#id_autores").on("select2:select", function (evt) {
            var element = evt.params.data.element;
            var $element = $(element);

            $element.detach();
            $(this).append($element);
            $(this).trigger("change");
        });
    </script>
{% endblock %}

{% block form_detalle %}
    <p><strong>Título del capítulo:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Título del capítulo, no del libro.">
            <i class="fa fa-question-circle"></i>
        </a> <i class="fa fa-edit"></i>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group date">
            <div class="input-group-addon">
                <i class="fa fa-pencil-square-o"></i>
            </div>
            {{ form.titulo }}
        </div>
    </div>
    </p>
    <p><strong>Libro:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Libro al que pertenece el capítulo escrito.">
            <i class="fa fa-question-circle"></i>
        </a> <i class="fa fa-edit"></i>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-book"></i></div>
            {{ form.libro }}
            <div class="input-group-addon">
                <a href="/nucleo/libros" data-toggle="tooltip" data-placement="left"
                   title="Mostrar los detalles adicionales del libro seleccionado.">
                    <i class="fa fa-eye"></i>
                </a>
            </div>
            <div class="input-group-addon">
                <a href="/divulgacion-cientifica/libros-divulgacion" data-toggle="tooltip" data-placement="left"
                   title="Agregar un libro nuevo. Cuando no existe en los registros, aquí se puede dar de alta.">
                    <i class="fa fa-plus"></i>
                </a>
            </div>
        </div>
    </div>
    </p>
    <p><strong>Autores del capítulo:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Autores del capítulo, sólo autores que estén adscritos al CIGA.">
            <i class="fa fa-question-circle"></i></a> <i class="fa fa-edit"></i>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group">
            <div class="input-group-addon"><i class="fa fa-users"></i></div>
            {{ form.autores }}
            <div class="input-group-addon">
                <a href="#" data-toggle="tooltip" data-placement="left"
                   title="Mostrar los detalles adicionales de los autores.">
                    <i class="fa fa-eye"></i>
                </a>
            </div>
            <div class="input-group-addon">
                <a href="/nucleo/usuarios/" data-toggle="tooltip" data-placement="left" target="_blank"
                   title="Agregar un autor nuevo. Cuando no existe en los registros, aquí se puede dar de alta.">
                    <i class="fa fa-plus"></i>
                </a>
            </div>
        </div>
    </div>
    </p>
    <p><strong>Autores como se reportan en el capítulo: <a href="#" data-toggle="tooltip" data-placement="right"
                                                        title="Autores tal cual se reportan en el capítulo, en el orden y forma.">
        <i class="fa fa-question-circle"></i></a></strong>
        {{ form.autores_todos }}
    </p>
    <p><strong>Página inicial:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Número de página donde inicia el capítulo.">
            <i class="fa fa-question-circle"></i></a> <i class="fa fa-edit"></i>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group date">
            <div class="input-group-addon"><i class="fa fa-sort-numeric-desc"></i></div>
            {{ form.pagina_inicio }}
        </div>
    </div>
    </p>
    <p><strong>Página final:</strong>
        <a href="#" data-toggle="tooltip" data-placement="right"
           title="Número de página donde finaliza el capítulo.">
            <i class="fa fa-question-circle"></i></a> <i class="fa fa-edit"></i>
    <div class="form-group" style="margin-top: -10px;">
        <div class="input-group date">
            <div class="input-group-addon"><i class="fa fa-sort-numeric-desc"></i></div>
            {{ form.pagina_fin }}
        </div>
    </div>
    </p>

    <script>
        $("#id_autores").on("select2:select", function (evt) {
            var element = evt.params.data.element;
            var $element = $(element);
            $element.detach();
            $(this).append($element);
            $(this).trigger("change");
        });
    </script>

{% endblock %}